services:
  cache:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - .temp/redis:/data

  pocketbase:
    image: elestio/pocketbase:latest
    restart: always
    ports:
      - '8090:8090'
    volumes:
      - ./.pocketbase/pb_data:/pb_data
      - ./.pocketbase/pb_public:/pb_public
      - ./.pocketbase/pb_migrations:/pb_migrations
